remove licence from pyproject.toml because setuptools complains about it...
The error output is:

ValueError: invalid pyproject.toml config: `project`.
configuration error: `project` must not contain {'licence'} properties